charts: add missing helm dep
fixes,

❯ make upgrade
export KUBECONFIG=~/.kube/config_kind
kubectl config use-context kind-kind
Switched to context "kind-kind".
helm upgrade hollow-sandbox . -f values.yaml -f values-nats.yaml
Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in
charts/ directory: prometheus-pushgateway
make: *** [upgrade] Error 1